### PR TITLE
Fix KK version of ClothingStateMenuX attempting to hook KKS version of MoreOutfits assembly

### PR DESCRIPTION
**Pull request by Kokaiinum**

### CODE REVIEW

**Review by ManlyMarco — COMMENTED** [review]
Why not do an `#if KK` on the HarmonyPatch attribute instead? Seems far simpler than this.

**Comment by Kokaiinum** [comment]
In hindsight, yes. Added this change.

**Comment by Keelhauled** [comment]
Are the .sln changes necessary? Also move the brackets to their own lines.

**Comment by Kokaiinum** [comment]
The .sln changes were done automatically by VS, I didn't touch that. So they're probably not neccessary? I can revert them if you prefer

**Comment by Keelhauled** [comment]
It's pretty easy to pick just what actually needs to be committed with git. I assume it's just that HarmonyPostfix change so about 5 lines.

**Pull request merged**
